name: Docker Build & Publish

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'task.md'
      - 'implementation_plan.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and Push Backend
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./Order-Management
          file: ./Order-Management/Dockerfile
          push: true
          tags: nandyalasivasaidanush/ecommerce-backend:latest

      # Build and Push Frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./ecommerceorder-frontend
          file: ./ecommerceorder-frontend/Dockerfile
          push: true
          tags: nandyalasivasaidanush/ecommerce-frontend:latest
